# Created using wingetcreate

PackageIdentifier: Timber1900.WebDL
PackageVersion: v9.2
PackageLocale: en-US
Publisher: Timber1900
PackageName: WebDL
License: MIT License
ShortDescription: WebDL Setup
ManifestType: defaultLocale
ManifestVersion: 1.0.0
