---
name: Feature request
about: Request a new feature for Youtube Downloader
title: ''
labels: 'Feature request'
assignees: timber1900
---

**Describe your idea**
A clear and concise description of your idea.

**Propose a way to implement it**
If possible propose, using code or not, a way to implement your idea
