# Created using wingetcreate

PackageIdentifier: Timber1900.WebDL
PackageVersion: v10
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/Timber1900/WebDL/releases/download/v10/WebDL.exe
  InstallerSha256: f3fe3e7c70b8a8c2c3eb7c37d84f594d278a25ad8f44b4b80b3e98237e0f94c5
ManifestType: installer
ManifestVersion: 1.0.0
